<?php

namespace Database\Seeders;

use App\Models\Transaction;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class TransactionSeeder extends Seeder
{
    public function run(): void
    {
        // Get or create a dummy user
        $user = User::first();

        $transactions = [
            [
                'status' => 'completed',
                'product_name' => 'Mobile Legends 86 Diamonds',
                'category_name' => 'Mobile Legends',
                'product_price' => 20000,
                'total_amount' => 21500,
                'admin_fee' => 1500,
                'payment_method' => 'QRIS',
                'payment_channel' => 'qris',
                'customer_name' => 'Andi Saputra',
                'customer_email' => 'andi@gmail.com',
                'customer_phone' => '081234567890',
                'paid_at' => now()->subDays(1),
                'completed_at' => now()->subDays(1)->addMinutes(5),
                'admin_note' => 'Pengiriman berhasil otomatis',
                'ip_address' => '103.154.92.45',
                'order_data' => ['user_id' => '123456789', 'zone_id' => '1234'],
            ],
            [
                'status' => 'paid',
                'product_name' => 'Free Fire 720 Diamonds',
                'category_name' => 'Free Fire',
                'product_price' => 100000,
                'total_amount' => 102000,
                'admin_fee' => 2000,
                'payment_method' => 'BCA VA',
                'payment_channel' => 'bca_va',
                'customer_name' => 'Budi Hartono',
                'customer_email' => 'budi.h@gmail.com',
                'customer_phone' => '082198765432',
                'paid_at' => now()->subHours(3),
                'admin_note' => null,
                'ip_address' => '182.1.78.92',
                'order_data' => ['user_id' => '987654321'],
            ],
            [
                'status' => 'processing',
                'product_name' => 'PUBG Mobile 660 UC',
                'category_name' => 'PUBG Mobile',
                'product_price' => 150000,
                'total_amount' => 152500,
                'admin_fee' => 2500,
                'payment_method' => 'GoPay',
                'payment_channel' => 'gopay',
                'customer_name' => 'Citra Dewi',
                'customer_email' => 'citra.d@yahoo.com',
                'customer_phone' => '085312345678',
                'paid_at' => now()->subHours(1),
                'admin_note' => 'Sedang menunggu response provider',
                'ip_address' => '36.90.12.145',
                'order_data' => ['user_id' => '5432167890'],
            ],
            [
                'status' => 'pending',
                'product_name' => 'Genshin Impact 300+30 Genesis Crystal',
                'category_name' => 'Genshin Impact',
                'product_price' => 75000,
                'total_amount' => 77000,
                'admin_fee' => 2000,
                'payment_method' => 'DANA',
                'payment_channel' => 'dana',
                'customer_name' => 'Dian Permata',
                'customer_email' => 'dian.p@gmail.com',
                'customer_phone' => '087890123456',
                'admin_note' => null,
                'ip_address' => '114.124.211.98',
                'order_data' => ['server' => 'Asia', 'uid' => '812345678'],
            ],
            [
                'status' => 'failed',
                'product_name' => 'Valorant 1000 VP',
                'category_name' => 'Valorant',
                'product_price' => 150000,
                'total_amount' => 153000,
                'admin_fee' => 3000,
                'payment_method' => 'BRI VA',
                'payment_channel' => 'bri_va',
                'customer_name' => 'Eka Prasetyo',
                'customer_email' => 'eka.p@hotmail.com',
                'customer_phone' => '081987654321',
                'paid_at' => now()->subDays(2),
                'admin_note' => 'Provider gagal proses, perlu refund',
                'ip_address' => '202.67.38.156',
                'order_data' => ['riot_id' => 'EkaPras#1234'],
            ],
            [
                'status' => 'cancelled',
                'product_name' => 'Mobile Legends Weekly Diamond Pass',
                'category_name' => 'Mobile Legends',
                'product_price' => 28000,
                'total_amount' => 29500,
                'admin_fee' => 1500,
                'payment_method' => 'OVO',
                'payment_channel' => 'ovo',
                'customer_name' => 'Fajar Nugroho',
                'customer_email' => 'fajar.n@gmail.com',
                'customer_phone' => '089612345678',
                'admin_note' => 'Dibatalkan oleh pembeli',
                'ip_address' => '125.162.45.78',
                'order_data' => ['user_id' => '111222333', 'zone_id' => '4455'],
            ],
            [
                'status' => 'completed',
                'product_name' => 'Honkai Star Rail 300 Oneiric Shard',
                'category_name' => 'Honkai Star Rail',
                'product_price' => 75000,
                'total_amount' => 77500,
                'admin_fee' => 2500,
                'payment_method' => 'Mandiri VA',
                'payment_channel' => 'mandiri_va',
                'customer_name' => 'Gita Maharani',
                'customer_email' => 'gita.m@gmail.com',
                'customer_phone' => '081345678901',
                'paid_at' => now()->subDays(3),
                'completed_at' => now()->subDays(3)->addMinutes(3),
                'admin_note' => null,
                'ip_address' => '180.244.12.67',
                'order_data' => ['uid' => '901234567', 'server' => 'Asia'],
            ],
            [
                'status' => 'paid',
                'product_name' => 'Free Fire Membership Mingguan',
                'category_name' => 'Free Fire',
                'product_price' => 15000,
                'total_amount' => 16500,
                'admin_fee' => 1500,
                'payment_method' => 'ShopeePay',
                'payment_channel' => 'shopeepay',
                'customer_name' => 'Hendra Wijaya',
                'customer_email' => 'hendra.w@gmail.com',
                'customer_phone' => '082234567890',
                'paid_at' => now()->subMinutes(45),
                'admin_note' => 'Menunggu diproses admin',
                'ip_address' => '103.20.188.34',
                'order_data' => ['user_id' => '654321987'],
            ],
            [
                'status' => 'completed',
                'product_name' => 'Steam Wallet IDR 60.000',
                'category_name' => 'Steam',
                'product_price' => 62000,
                'total_amount' => 64000,
                'admin_fee' => 2000,
                'payment_method' => 'QRIS',
                'payment_channel' => 'qris',
                'customer_name' => 'Indra Kusuma',
                'customer_email' => 'indra.k@outlook.com',
                'customer_phone' => '085678901234',
                'paid_at' => now()->subDays(5),
                'completed_at' => now()->subDays(5)->addMinutes(2),
                'admin_note' => null,
                'ip_address' => '110.137.78.45',
                'order_data' => ['email_steam' => 'indra_steam@gmail.com'],
            ],
            [
                'status' => 'paid',
                'product_name' => 'PUBG Mobile Royale Pass',
                'category_name' => 'PUBG Mobile',
                'product_price' => 80000,
                'total_amount' => 82500,
                'admin_fee' => 2500,
                'payment_method' => 'BNI VA',
                'payment_channel' => 'bni_va',
                'customer_name' => 'Joko Susilo',
                'customer_email' => 'joko.s@gmail.com',
                'customer_phone' => '081567890123',
                'paid_at' => now()->subHours(2),
                'admin_note' => null,
                'ip_address' => '36.68.192.87',
                'order_data' => ['user_id' => '5123456789'],
            ],
            [
                'status' => 'complain',
                'product_name' => 'Mobile Legends 172 Diamonds',
                'category_name' => 'Mobile Legends',
                'product_price' => 38000,
                'total_amount' => 39500,
                'admin_fee' => 1500,
                'payment_method' => 'QRIS',
                'payment_channel' => 'qris',
                'customer_name' => 'Kevin Saputra',
                'customer_email' => 'kevin.s@gmail.com',
                'customer_phone' => '081234509876',
                'paid_at' => now()->subDays(1),
                'admin_note' => 'Diamond belum masuk, pembeli komplain via WA',
                'ip_address' => '103.47.132.67',
                'order_data' => ['user_id' => '445566778', 'zone_id' => '1122'],
            ],
        ];

        foreach ($transactions as $i => $data) {
            $invoiceNum = 'INV-' . now()->format('Ymd') . '-' . str_pad($i + 1, 4, '0', STR_PAD_LEFT);
            $orderId = 'ORD-' . Str::upper(Str::random(8));

            Transaction::create(array_merge($data, [
                'order_id' => $orderId,
                'invoice_number' => $invoiceNum,
                'user_id' => $user?->id,
                'quantity' => 1,
                'discount' => 0,
                'payment_expired_at' => $data['status'] === 'pending' ? now()->addHours(24) : null,
                'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
                'order_data' => $data['order_data'],
                'created_at' => now()->subDays(rand(0, 7))->subHours(rand(0, 12)),
            ]));
        }
    }
}
